name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: ENV
      run: export TOKEN_VK={{TOKEN_VK}}
    - name: Run
      env: 
        TOKEN_VK: ${{ secrets.TOKEN_VK }}
      run: nohup go run -v ./src &

